[package]
name = "binwrite_derive"
version = "0.1.1"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"
description = "Derive macro for binwrite"
repository = "https://github.com/jam1garner/binwrite_derive"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^1.0.7", features = ["extra-traits"] }
quote = "^1.0.2"
proc-macro2 = "^1.0.6"

[dev-dependencies]
binwrite = "*"

