name: Rust Build and Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
        - master
        # TODO: remove
        - binread_remerge

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Local-only setup
      if: ${{ env.ACT }}
      run: |
        # For local setups building with `act`, rustup likely won't be installed
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Build
      # Build/test uses absolute(ish) paths, to maintain compatibility with `act`
      run: ~/.cargo/bin/cargo build
    - name: Build no_std
      run: ~/.cargo/bin/cargo build -p binrw --no-default-features
    - name: Test
      run: ~/.cargo/bin/cargo test

